"""update text blocks

Revision ID: 2f9170c7585a
Revises: 66140cf69a69
Create Date: 2024-08-30 13:40:19.529461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9170c7585a'
down_revision: Union[str, None] = '66140cf69a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_block', 'text', new_column_name='label')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_block', 'label', new_column_name='text')
    # ### end Alembic commands ###
