"""delete cascade2

Revision ID: 3f2a417a19f1
Revises: c5cfeb408455
Create Date: 2024-09-05 18:57:28.155885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2a417a19f1'
down_revision: Union[str, None] = 'c5cfeb408455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mobility_result_indicators_mobility_subresult_id_fkey', 'mobility_result_indicators', type_='foreignkey')
    op.drop_constraint('mobility_result_indicators_indicator_id_fkey', 'mobility_result_indicators', type_='foreignkey')
    op.create_foreign_key(None, 'mobility_result_indicators', 'mobility_subresult', ['mobility_subresult_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'mobility_result_indicators', 'indicator', ['indicator_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('text_block_tag_tag_id_fkey', 'text_block_tag', type_='foreignkey')
    op.drop_constraint('text_block_tag_text_block_id_fkey', 'text_block_tag', type_='foreignkey')
    op.create_foreign_key(None, 'text_block_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'text_block_tag', 'text_block', ['text_block_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text_block_tag', type_='foreignkey')
    op.drop_constraint(None, 'text_block_tag', type_='foreignkey')
    op.create_foreign_key('text_block_tag_text_block_id_fkey', 'text_block_tag', 'text_block', ['text_block_id'], ['id'])
    op.create_foreign_key('text_block_tag_tag_id_fkey', 'text_block_tag', 'tag', ['tag_id'], ['id'])
    op.drop_constraint(None, 'mobility_result_indicators', type_='foreignkey')
    op.drop_constraint(None, 'mobility_result_indicators', type_='foreignkey')
    op.create_foreign_key('mobility_result_indicators_indicator_id_fkey', 'mobility_result_indicators', 'indicator', ['indicator_id'], ['id'])
    op.create_foreign_key('mobility_result_indicators_mobility_subresult_id_fkey', 'mobility_result_indicators', 'mobility_subresult', ['mobility_subresult_id'], ['id'])
    # ### end Alembic commands ###
