"""add user role

Revision ID: 787930773226
Revises: c099004fe40d
Create Date: 2024-10-23 17:07:14.197201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '787930773226'
down_revision: Union[str, None] = 'c099004fe40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Define the RoleEnum again here to be used in the migration
role_enum = postgresql.ENUM('admin', 'administration', 'politician', name='roleenum')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the role enum type and add it to the user table
    role_enum.create(op.get_bind())  # Create the enum type in PostgreSQL
    op.add_column('user', sa.Column('role', role_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the role column and drop the enum type
    op.drop_column('user', 'role')
    role_enum.drop(op.get_bind())  # Drop the enum type
    # ### end Alembic commands ###
