"""add autor gemeinde gebiet

Revision ID: b183a5107041
Revises: fda26a8974b8
Create Date: 2025-08-20 11:21:06.113020

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = "b183a5107041"
down_revision: Union[str, None] = "fda26a8974b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gemeinde_gebiet",
        sa.Column(
            "erstellt_von",
            GUID(),
            nullable=True,
            comment="User ID des Erstellers des Indikators",
        ),
    )
    op.add_column(
        "gemeinde_gebiet",
        sa.Column(
            "zuletzt_bearbeitet_von",
            GUID(),
            nullable=True,
            comment="User ID des zuletzt bearbeitenden Benutzers",
        ),
    )
    op.create_foreign_key(
        None,
        "gemeinde_gebiet",
        "user",
        ["zuletzt_bearbeitet_von"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None, "gemeinde_gebiet", "user", ["erstellt_von"], ["id"], ondelete="SET NULL"
    )
    op.alter_column(
        "tag",
        "gemeindespezifisch",
        existing_type=sa.BOOLEAN(),
        comment="Gibt an, ob der Tag mit anderen Gemeinden geteilt wird oder gemeindespezifisch ist",
        existing_comment="Gibt an, ob der Tag mit anderen Gemeinden geteilt wird oder geteilt wird",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user",
        "rolle_id",
        existing_type=sa.INTEGER(),
        comment="Rolle ID des Benutzers",
        existing_comment="Gemeinde ID, mit der der Benutzer verknüpft ist",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "rolle_id",
        existing_type=sa.INTEGER(),
        comment="Gemeinde ID, mit der der Benutzer verknüpft ist",
        existing_comment="Rolle ID des Benutzers",
        existing_nullable=False,
    )
    op.alter_column(
        "tag",
        "gemeindespezifisch",
        existing_type=sa.BOOLEAN(),
        comment="Gibt an, ob der Tag mit anderen Gemeinden geteilt wird oder geteilt wird",
        existing_comment="Gibt an, ob der Tag mit anderen Gemeinden geteilt wird oder gemeindespezifisch ist",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_constraint(None, "gemeinde_gebiet", type_="foreignkey")
    op.drop_constraint(None, "gemeinde_gebiet", type_="foreignkey")
    op.drop_column("gemeinde_gebiet", "zuletzt_bearbeitet_von")
    op.drop_column("gemeinde_gebiet", "erstellt_von")
    # ### end Alembic commands ###
