"""fix type climate_submission

Revision ID: b204b90d939e
Revises: bc641731e773
Create Date: 2025-03-12 12:44:43.316935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b204b90d939e'
down_revision: Union[str, None] = 'bc641731e773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('climate_submission', 'impact_duration',
               existing_type=postgresql.ENUM('short', 'medium', 'long', name='impactdurationenum'),
               type_=sa.String(),
               existing_comment='Estimated duration of the impact (e.g., short, medium, long).',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('climate_submission', 'impact_duration',
               existing_type=sa.String(),
               type_=postgresql.ENUM('short', 'medium', 'long', name='impactdurationenum'),
               existing_comment='Estimated duration of the impact (e.g., short, medium, long).',
               existing_nullable=True)
    # ### end Alembic commands ###
