"""fix renaming bugs mobilitäaetscheck eingabe ziel ober

Revision ID: c32c9e65cb91
Revises: da068b9a5578
Create Date: 2025-07-15 17:28:55.576397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c32c9e65cb91"
down_revision: Union[str, None] = "da068b9a5578"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "mobilitaetscheck_eingabe_ziel_mobilitaetscheck_ziel_ober_i_fkey",
        "mobilitaetscheck_eingabe_ziel_ober",
        type_="foreignkey",
    )
    op.drop_constraint(
        "mobilitaetscheck_eingabe_ziel__mobilitaetscheck_eingabe_id_fkey",
        "mobilitaetscheck_eingabe_ziel_ober",
        type_="foreignkey",
    )
    op.alter_column(
        "mobilitaetscheck_eingabe_ziel_ober",
        "mobilitaetscheck_eingabe_id",
        new_column_name="eingabe_id",
        existing_type=sa.Integer(),
        comment="Eingabe ID des Mobilitätschecks, mit der das Oberziel verknüpft ist",
    )

    op.alter_column(
        "mobilitaetscheck_eingabe_ziel_ober",
        "mobilitaetscheck_ziel_ober_id",
        new_column_name="ziel_ober_id",
        existing_type=sa.Integer(),
        comment="ID des Leitziels, mit dem die Eingabe verknüpft ist",
    )

    op.create_foreign_key(
        None,
        "mobilitaetscheck_eingabe_ziel_ober",
        "mobilitaetscheck_eingabe",
        ["eingabe_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "mobilitaetscheck_eingabe_ziel_ober",
        "mobilitaetscheck_ziel_ober",
        ["ziel_ober_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "mobilitaetscheck_eingabe_ziel_ober", type_="foreignkey")
    op.drop_constraint(None, "mobilitaetscheck_eingabe_ziel_ober", type_="foreignkey")
    op.alter_column(
        "mobilitaetscheck_eingabe_ziel_ober",
        "eingabe_id",
        new_column_name="mobilitaetscheck_eingabe_id",
        existing_type=sa.Integer(),
        comment="Eingabe ID des Mobilitätschecks, mit der das Oberziel verknüpft ist",
    )

    op.alter_column(
        "mobilitaetscheck_eingabe_ziel_ober",
        "ziel_ober_id",
        new_column_name="mobilitaetscheck_ziel_ober_id",
        existing_type=sa.Integer(),
        comment="ID des Leitziels, mit dem die Eingabe verknüpft ist",
    )

    op.create_foreign_key(
        "mobilitaetscheck_eingabe_ziel__mobilitaetscheck_eingabe_id_fkey",
        "mobilitaetscheck_eingabe_ziel_ober",
        "mobilitaetscheck_eingabe",
        ["mobilitaetscheck_eingabe_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "mobilitaetscheck_eingabe_ziel_mobilitaetscheck_ziel_ober_i_fkey",
        "mobilitaetscheck_eingabe_ziel_ober",
        "mobilitaetscheck_ziel_ober",
        ["mobilitaetscheck_ziel_ober_id"],
        ["id"],
    )
    op.drop_column("mobilitaetscheck_eingabe_ziel_ober", "ziel_ober_id")
    op.drop_column("mobilitaetscheck_eingabe_ziel_ober", "eingabe_id")
    # ### end Alembic commands ###
