"""rename subresult

Revision ID: d47b21bc9892
Revises: dfe2ecad274e
Create Date: 2024-09-05 14:44:59.214255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47b21bc9892'
down_revision: Union[str, None] = 'dfe2ecad274e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('mobility_result_sub', 'mobility_subresult')
    op.create_index(op.f('ix_mobility_subresult_id'), 'mobility_subresult', ['id'], unique=True)
    op.drop_index('ix_mobility_result_sub_id', table_name='mobility_result_sub')
    op.alter_column('mobility_result_indicators', 'mobility_result_sub_id', new_column_name='mobility_subresult_id')
    op.drop_constraint('mobility_result_indicators_mobility_result_sub_id_fkey', 'mobility_result_indicators', type_='foreignkey')
    op.create_foreign_key(None, 'mobility_result_indicators', 'mobility_subresult', ['mobility_subresult_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('mobility_subresult', 'mobility_result_sub')
    op.alter_column('mobility_result_indicators', 'mobility_subresult_id', new_column_name='mobility_result_sub_id')
    op.drop_constraint(None, 'mobility_result_indicators', type_='foreignkey')
    op.create_foreign_key('mobility_result_indicators_mobility_result_sub_id_fkey', 'mobility_result_indicators', 'mobility_result_sub', ['mobility_result_sub_id'], ['id'])
    op.create_index('ix_mobility_result_sub_id', 'mobility_result_sub', ['id'], unique=True)
    op.drop_index(op.f('ix_mobility_subresult_id'), table_name='mobility_subresult')
    # ### end Alembic commands ###
