"""add author and editor col

Revision ID: e1ab718e686d
Revises: 3297a033ac1c
Create Date: 2024-10-25 12:16:27.815284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = 'e1ab718e686d'
down_revision: Union[str, None] = '3297a033ac1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climate_submission', sa.Column('created_by', GUID(), nullable=True))
    op.add_column('climate_submission', sa.Column('last_edited_by', GUID(), nullable=True))
    op.create_foreign_key(None, 'climate_submission', 'user', ['last_edited_by'], ['id'])
    op.create_foreign_key(None, 'climate_submission', 'user', ['created_by'], ['id'])
    op.drop_column('climate_submission', 'author')
    op.add_column('indicator', sa.Column('created_by', GUID(), nullable=True))
    op.add_column('indicator', sa.Column('last_edited_by', GUID(), nullable=True))
    op.create_foreign_key(None, 'indicator', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'indicator', 'user', ['last_edited_by'], ['id'])
    op.add_column('main_objective', sa.Column('created_by', GUID(), nullable=True))
    op.add_column('main_objective', sa.Column('last_edited_by', GUID(), nullable=True))
    op.create_foreign_key(None, 'main_objective', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'main_objective', 'user', ['last_edited_by'], ['id'])
    op.drop_constraint('mobility_result_municipality_id_fkey', 'mobility_result', type_='foreignkey')
    op.drop_column('mobility_result', 'municipality_id')
    op.add_column('mobility_submission', sa.Column('created_by', GUID(), nullable=True))
    op.add_column('mobility_submission', sa.Column('last_edited_by', GUID(), nullable=True))
    op.create_foreign_key(None, 'mobility_submission', 'user', ['last_edited_by'], ['id'])
    op.create_foreign_key(None, 'mobility_submission', 'user', ['created_by'], ['id'])
    op.drop_column('mobility_submission', 'author')
    op.drop_constraint('mobility_subresult_municipality_id_fkey', 'mobility_subresult', type_='foreignkey')
    op.drop_column('mobility_subresult', 'municipality_id')
    op.add_column('sub_objective', sa.Column('created_by', GUID(), nullable=True))
    op.add_column('sub_objective', sa.Column('last_edited_by', GUID(), nullable=True))
    op.create_foreign_key(None, 'sub_objective', 'user', ['last_edited_by'], ['id'])
    op.create_foreign_key(None, 'sub_objective', 'user', ['created_by'], ['id'])
    op.add_column('tag', sa.Column('created_by', GUID(), nullable=True))
    op.add_column('tag', sa.Column('last_edited_by', GUID(), nullable=True))
    op.create_foreign_key(None, 'tag', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'tag', 'user', ['last_edited_by'], ['id'])
    op.add_column('text_block', sa.Column('created_by', GUID(), nullable=True))
    op.add_column('text_block', sa.Column('last_edited_by', GUID(), nullable=True))
    op.create_foreign_key(None, 'text_block', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'text_block', 'user', ['last_edited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text_block', type_='foreignkey')
    op.drop_constraint(None, 'text_block', type_='foreignkey')
    op.drop_column('text_block', 'last_edited_by')
    op.drop_column('text_block', 'created_by')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'last_edited_by')
    op.drop_column('tag', 'created_by')
    op.drop_constraint(None, 'sub_objective', type_='foreignkey')
    op.drop_constraint(None, 'sub_objective', type_='foreignkey')
    op.drop_column('sub_objective', 'last_edited_by')
    op.drop_column('sub_objective', 'created_by')
    op.add_column('mobility_subresult', sa.Column('municipality_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('mobility_subresult_municipality_id_fkey', 'mobility_subresult', 'municipality', ['municipality_id'], ['id'])
    op.add_column('mobility_submission', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mobility_submission', type_='foreignkey')
    op.drop_constraint(None, 'mobility_submission', type_='foreignkey')
    op.drop_column('mobility_submission', 'last_edited_by')
    op.drop_column('mobility_submission', 'created_by')
    op.add_column('mobility_result', sa.Column('municipality_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('mobility_result_municipality_id_fkey', 'mobility_result', 'municipality', ['municipality_id'], ['id'])
    op.drop_constraint(None, 'main_objective', type_='foreignkey')
    op.drop_constraint(None, 'main_objective', type_='foreignkey')
    op.drop_column('main_objective', 'last_edited_by')
    op.drop_column('main_objective', 'created_by')
    op.drop_constraint(None, 'indicator', type_='foreignkey')
    op.drop_constraint(None, 'indicator', type_='foreignkey')
    op.drop_column('indicator', 'last_edited_by')
    op.drop_column('indicator', 'created_by')
    op.add_column('climate_submission', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'climate_submission', type_='foreignkey')
    op.drop_constraint(None, 'climate_submission', type_='foreignkey')
    op.drop_column('climate_submission', 'last_edited_by')
    op.drop_column('climate_submission', 'created_by')
    # ### end Alembic commands ###
