"""add alter role to string

Revision ID: e213d69a710b
Revises: 787930773226
Create Date: 2024-10-23 18:52:07.234314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e213d69a710b'
down_revision: Union[str, None] = '787930773226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'administration', 'politician', name='roleenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('admin', 'administration', 'politician', name='roleenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
