"""magistratsvorlage user info

Revision ID: 44e6e07b9cb0
Revises: c77fba81521e
Create Date: 2025-07-30 17:15:15.732519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = "44e6e07b9cb0"
down_revision: Union[str, None] = "c77fba81521e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "magistratsvorlage",
        sa.Column(
            "erstellt_von",
            GUID(),
            nullable=True,
            comment="User ID vom Ersteller des Klimachecks",
        ),
    )
    op.add_column(
        "magistratsvorlage",
        sa.Column(
            "zuletzt_bearbeiter_von",
            GUID(),
            nullable=True,
            comment="User ID des zuletzt bearbeitenden Benutzers",
        ),
    )
    op.create_foreign_key(
        None,
        "magistratsvorlage",
        "user",
        ["zuletzt_bearbeiter_von"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None, "magistratsvorlage", "user", ["erstellt_von"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "magistratsvorlage", type_="foreignkey")
    op.drop_constraint(None, "magistratsvorlage", type_="foreignkey")
    op.drop_column("magistratsvorlage", "zuletzt_bearbeiter_von")
    op.drop_column("magistratsvorlage", "erstellt_von")
    # ### end Alembic commands ###
