"""remove not needed attributes from klimareleanzpruefung

Revision ID: 475d7faf351c
Revises: 66c4eec9485b
Create Date: 2026-02-03 16:47:43.345778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475d7faf351c'
down_revision: Union[str, None] = '66c4eec9485b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb1_gemeinde_id_fkey'), 'klimarelevanzpruefung_eingabe_fb1', type_='foreignkey')
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb1_erstellt_von_fkey'), 'klimarelevanzpruefung_eingabe_fb1', type_='foreignkey')
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb1_zuletzt_bearbeitet_von_fkey'), 'klimarelevanzpruefung_eingabe_fb1', type_='foreignkey')
    op.drop_column('klimarelevanzpruefung_eingabe_fb1', 'zuletzt_bearbeitet_von')
    op.drop_column('klimarelevanzpruefung_eingabe_fb1', 'erstellt_von')
    op.drop_column('klimarelevanzpruefung_eingabe_fb1', 'gemeinde_id')
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb2_erstellt_von_fkey'), 'klimarelevanzpruefung_eingabe_fb2', type_='foreignkey')
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb2_zuletzt_bearbeitet_von_fkey'), 'klimarelevanzpruefung_eingabe_fb2', type_='foreignkey')
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb2_gemeinde_id_fkey'), 'klimarelevanzpruefung_eingabe_fb2', type_='foreignkey')
    op.drop_column('klimarelevanzpruefung_eingabe_fb2', 'zuletzt_bearbeitet_von')
    op.drop_column('klimarelevanzpruefung_eingabe_fb2', 'erstellt_von')
    op.drop_column('klimarelevanzpruefung_eingabe_fb2', 'gemeinde_id')
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb3_erstellt_von_fkey'), 'klimarelevanzpruefung_eingabe_fb3', type_='foreignkey')
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb3_gemeinde_id_fkey'), 'klimarelevanzpruefung_eingabe_fb3', type_='foreignkey')
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb3_zuletzt_bearbeitet_von_fkey'), 'klimarelevanzpruefung_eingabe_fb3', type_='foreignkey')
    op.drop_column('klimarelevanzpruefung_eingabe_fb3', 'zuletzt_bearbeitet_von')
    op.drop_column('klimarelevanzpruefung_eingabe_fb3', 'erstellt_von')
    op.drop_column('klimarelevanzpruefung_eingabe_fb3', 'gemeinde_id')
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb4_zuletzt_bearbeitet_von_fkey'), 'klimarelevanzpruefung_eingabe_fb4', type_='foreignkey')
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb4_gemeinde_id_fkey'), 'klimarelevanzpruefung_eingabe_fb4', type_='foreignkey')
    op.drop_constraint(op.f('klimarelevanzpruefung_eingabe_fb4_erstellt_von_fkey'), 'klimarelevanzpruefung_eingabe_fb4', type_='foreignkey')
    op.drop_column('klimarelevanzpruefung_eingabe_fb4', 'zuletzt_bearbeitet_von')
    op.drop_column('klimarelevanzpruefung_eingabe_fb4', 'erstellt_von')
    op.drop_column('klimarelevanzpruefung_eingabe_fb4', 'gemeinde_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('klimarelevanzpruefung_eingabe_fb4', sa.Column('gemeinde_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Gemeinde ID'))
    op.add_column('klimarelevanzpruefung_eingabe_fb4', sa.Column('erstellt_von', sa.UUID(), autoincrement=False, nullable=True, comment='User ID des Erstellers'))
    op.add_column('klimarelevanzpruefung_eingabe_fb4', sa.Column('zuletzt_bearbeitet_von', sa.UUID(), autoincrement=False, nullable=True, comment='User ID des zuletzt bearbeitenden Benutzers'))
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb4_erstellt_von_fkey'), 'klimarelevanzpruefung_eingabe_fb4', 'user', ['erstellt_von'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb4_gemeinde_id_fkey'), 'klimarelevanzpruefung_eingabe_fb4', 'gemeinde', ['gemeinde_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb4_zuletzt_bearbeitet_von_fkey'), 'klimarelevanzpruefung_eingabe_fb4', 'user', ['zuletzt_bearbeitet_von'], ['id'], ondelete='SET NULL')
    op.add_column('klimarelevanzpruefung_eingabe_fb3', sa.Column('gemeinde_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Gemeinde ID'))
    op.add_column('klimarelevanzpruefung_eingabe_fb3', sa.Column('erstellt_von', sa.UUID(), autoincrement=False, nullable=True, comment='User ID des Erstellers'))
    op.add_column('klimarelevanzpruefung_eingabe_fb3', sa.Column('zuletzt_bearbeitet_von', sa.UUID(), autoincrement=False, nullable=True, comment='User ID des zuletzt bearbeitenden Benutzers'))
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb3_zuletzt_bearbeitet_von_fkey'), 'klimarelevanzpruefung_eingabe_fb3', 'user', ['zuletzt_bearbeitet_von'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb3_gemeinde_id_fkey'), 'klimarelevanzpruefung_eingabe_fb3', 'gemeinde', ['gemeinde_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb3_erstellt_von_fkey'), 'klimarelevanzpruefung_eingabe_fb3', 'user', ['erstellt_von'], ['id'], ondelete='SET NULL')
    op.add_column('klimarelevanzpruefung_eingabe_fb2', sa.Column('gemeinde_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Gemeinde ID'))
    op.add_column('klimarelevanzpruefung_eingabe_fb2', sa.Column('erstellt_von', sa.UUID(), autoincrement=False, nullable=True, comment='User ID des Erstellers'))
    op.add_column('klimarelevanzpruefung_eingabe_fb2', sa.Column('zuletzt_bearbeitet_von', sa.UUID(), autoincrement=False, nullable=True, comment='User ID des zuletzt bearbeitenden Benutzers'))
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb2_gemeinde_id_fkey'), 'klimarelevanzpruefung_eingabe_fb2', 'gemeinde', ['gemeinde_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb2_zuletzt_bearbeitet_von_fkey'), 'klimarelevanzpruefung_eingabe_fb2', 'user', ['zuletzt_bearbeitet_von'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb2_erstellt_von_fkey'), 'klimarelevanzpruefung_eingabe_fb2', 'user', ['erstellt_von'], ['id'], ondelete='SET NULL')
    op.add_column('klimarelevanzpruefung_eingabe_fb1', sa.Column('gemeinde_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Gemeinde ID'))
    op.add_column('klimarelevanzpruefung_eingabe_fb1', sa.Column('erstellt_von', sa.UUID(), autoincrement=False, nullable=True, comment='User ID des Erstellers'))
    op.add_column('klimarelevanzpruefung_eingabe_fb1', sa.Column('zuletzt_bearbeitet_von', sa.UUID(), autoincrement=False, nullable=True, comment='User ID des zuletzt bearbeitenden Benutzers'))
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb1_zuletzt_bearbeitet_von_fkey'), 'klimarelevanzpruefung_eingabe_fb1', 'user', ['zuletzt_bearbeitet_von'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb1_erstellt_von_fkey'), 'klimarelevanzpruefung_eingabe_fb1', 'user', ['erstellt_von'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('klimarelevanzpruefung_eingabe_fb1_gemeinde_id_fkey'), 'klimarelevanzpruefung_eingabe_fb1', 'gemeinde', ['gemeinde_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
