"""add ClimateSubmission

Revision ID: 53b56f8d89cd
Revises: 1309540a7ffc
Create Date: 2024-08-29 13:05:11.394209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b56f8d89cd'
down_revision: Union[str, None] = '1309540a7ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('submission_no', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('impact', sa.Enum('positive', 'negative', 'no_effect', native_enum=False), nullable=False),
    sa.Column('impact_ghg', sa.Integer(), nullable=True),
    sa.Column('impact_adaption', sa.Integer(), nullable=True),
    sa.Column('impact_desc', sa.String(), nullable=True),
    sa.Column('impact_duration', sa.Enum('short', 'medium', 'long', native_enum=False), nullable=True),
    sa.Column('alternative_desc', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_submission_id'), 'climate_submission', ['id'], unique=True)
    op.drop_constraint('sub_target_key_target_id_fkey', 'sub_objective', type_='foreignkey')
    op.alter_column('sub_objective', 'key_target_id', new_column_name='main_objective_id')
    op.create_foreign_key(None, 'sub_objective', 'main_objective', ['main_objective_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_objective', 'main_objective_id', new_column_name='key_target_id')
    op.drop_constraint(None, 'sub_objective', type_='foreignkey')
    op.create_foreign_key('sub_target_key_target_id_fkey', 'sub_objective', 'main_objective', ['key_target_id'], ['id'])
    op.drop_index(op.f('ix_climate_submission_id'), table_name='climate_submission')
    op.drop_table('climate_submission')
    # ### end Alembic commands ###
