"""fix errors in klimarelevanzpruefung fb2

Revision ID: 66c4eec9485b
Revises: bc515597f5c5
Create Date: 2025-12-04 16:49:47.798302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66c4eec9485b"
down_revision: Union[str, None] = "bc515597f5c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "klimarelevanzpruefung_eingabe_fb2",
        "a2q1",
        new_column_name="b2q1",
        existing_type=sa.Integer(),
        comment="Teil 2 Frage 1",
    )

    op.alter_column(
        "klimarelevanzpruefung_eingabe_fb2",
        "a2q2",
        new_column_name="b2q2",
        existing_type=sa.String(),
        comment="Teil 2 Frage 2",
    )

    op.alter_column(
        "klimarelevanzpruefung_eingabe_fb2",
        "a2q3",
        new_column_name="b2q3",
        existing_type=sa.String(),
        comment="Teil 2 Frage 3",
    )

    op.alter_column(
        "klimarelevanzpruefung_eingabe_fb2",
        "a2q4",
        new_column_name="b2q4",
        existing_type=sa.Integer(),
        comment="Teil 2 Frage 4",
    )

    op.alter_column(
        "klimarelevanzpruefung_eingabe_fb2",
        "a2q5",
        new_column_name="b2q5",
        existing_type=sa.String(),
        comment="Teil 2 Frage 5",
    )

    # Constraints entfernen
    op.drop_constraint(
        "klimarelevanzpruefung_eingabe_fb2_a2q4_fkey",
        "klimarelevanzpruefung_eingabe_fb2",
        type_="foreignkey",
    )

    op.drop_constraint(
        "klimarelevanzpruefung_eingabe_fb2_a2q1_fkey",
        "klimarelevanzpruefung_eingabe_fb2",
        type_="foreignkey",
    )

    # Neue FKs für die umbenannten Spalten
    op.create_foreign_key(
        None,
        "klimarelevanzpruefung_eingabe_fb2",
        "bool_erweitert",
        ["b2q4"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_foreign_key(
        None,
        "klimarelevanzpruefung_eingabe_fb2",
        "bool_erweitert",
        ["b2q1"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "klimarelevanzpruefung_eingabe_fb2", type_="foreignkey")

    op.drop_constraint(None, "klimarelevanzpruefung_eingabe_fb2", type_="foreignkey")

    # Spalten zurück umbenennen
    op.alter_column(
        "klimarelevanzpruefung_eingabe_fb2",
        "b2q1",
        new_column_name="a2q1",
        existing_type=sa.Integer(),
    )

    op.alter_column(
        "klimarelevanzpruefung_eingabe_fb2",
        "b2q2",
        new_column_name="a2q2",
        existing_type=sa.String(),
    )

    op.alter_column(
        "klimarelevanzpruefung_eingabe_fb2",
        "b2q3",
        new_column_name="a2q3",
        existing_type=sa.String(),
    )

    op.alter_column(
        "klimarelevanzpruefung_eingabe_fb2",
        "b2q4",
        new_column_name="a2q4",
        existing_type=sa.Integer(),
    )

    op.alter_column(
        "klimarelevanzpruefung_eingabe_fb2",
        "b2q5",
        new_column_name="a2q5",
        existing_type=sa.String(),
    )

    # Alte Foreign Keys wiederherstellen
    op.create_foreign_key(
        "klimarelevanzpruefung_eingabe_fb2_a2q4_fkey",
        "klimarelevanzpruefung_eingabe_fb2",
        "bool_erweitert",
        ["a2q4"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_foreign_key(
        "klimarelevanzpruefung_eingabe_fb2_a2q1_fkey",
        "klimarelevanzpruefung_eingabe_fb2",
        "bool_erweitert",
        ["a2q1"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
