"""add relations

Revision ID: 79578ae70596
Revises: a8a693590fb2
Create Date: 2024-07-04 17:19:25.382560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79578ae70596'
down_revision: Union[str, None] = 'a8a693590fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators_tags',
    sa.Column('indicators_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indicators_id'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], )
    )
    op.create_table('text_blocks_tags',
    sa.Column('text_blocks_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['text_blocks_id'], ['text_blocks.id'], )
    )
    op.add_column('sub_targets', sa.Column('key_target_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sub_targets', 'key_targets', ['key_target_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_targets', type_='foreignkey')
    op.drop_column('sub_targets', 'key_target_id')
    op.drop_table('text_blocks_tags')
    op.drop_table('indicators_tags')
    # ### end Alembic commands ###
