"""fix typo

Revision ID: 83a75db6b1d5
Revises: 44e6e07b9cb0
Create Date: 2025-07-31 15:59:29.065771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "83a75db6b1d5"
down_revision: Union[str, None] = "44e6e07b9cb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "klimacheck_eingabe",
        "zuletzt_bearbeiter_von",
        new_column_name="zuletzt_bearbeitet_von",
    )
    op.drop_constraint(
        "klimacheck_eingabe_zuletzt_bearbeiter_von_fkey",
        "klimacheck_eingabe",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "klimacheck_eingabe",
        "user",
        ["zuletzt_bearbeitet_von"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "klimacheck_eingabe",
        "zuletzt_bearbeitet_von",
        new_column_name="zuletzt_bearbeiter_von",
    )
    op.drop_constraint(None, "klimacheck_eingabe", type_="foreignkey")
    op.create_foreign_key(
        "klimacheck_eingabe_zuletzt_bearbeiter_von_fkey",
        "klimacheck_eingabe",
        "user",
        ["zuletzt_bearbeiter_von"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
