"""delete enum climate_submission

Revision ID: 9e801d1375c7
Revises: b204b90d939e
Create Date: 2025-03-12 13:06:18.962976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e801d1375c7'
down_revision: Union[str, None] = 'b204b90d939e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('climate_submission', 'impact',
               existing_type=postgresql.ENUM('positive', 'negative', 'no_effect', name='impactenum'),
               type_=sa.String(),
               existing_comment='Estimated impact on climate (e.g., positive, negative, no effect).',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('climate_submission', 'impact',
               existing_type=sa.String(),
               type_=postgresql.ENUM('positive', 'negative', 'no_effect', name='impactenum'),
               existing_comment='Estimated impact on climate (e.g., positive, negative, no effect).',
               existing_nullable=False)
    # ### end Alembic commands ###
