"""add magistratsvorlage to klimareleanzpruefung

Revision ID: 9fb16fcb80af
Revises: e6453544b628
Create Date: 2026-02-04 11:19:09.560916

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fb16fcb80af"
down_revision: Union[str, None] = "e6453544b628"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "klimarelevanzpruefung_eingabe",
        sa.Column(
            "magistratsvorlage_id",
            sa.Integer(),
            nullable=True,
            comment="ID der zugehörigen Magistratsvorlage",
        ),
    )
    op.create_foreign_key(
        None,
        "klimarelevanzpruefung_eingabe",
        "magistratsvorlage",
        ["magistratsvorlage_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # Set all unset klimarelevanzpruefungen to magistratsvorlage_id = 6
    op.execute(
        "UPDATE klimarelevanzpruefung_eingabe SET magistratsvorlage_id = 6 WHERE magistratsvorlage_id IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "klimarelevanzpruefung_eingabe", type_="foreignkey")
    op.drop_column("klimarelevanzpruefung_eingabe", "magistratsvorlage_id")
    # ### end Alembic commands ###
