"""klimarelevanzpruefung

Revision ID: bc515597f5c5
Revises: bcd26d6bce92
Create Date: 2025-11-04 14:09:36.788677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "bc515597f5c5"
down_revision: Union[str, None] = "bcd26d6bce92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bool_erweitert",
        sa.Column("id", sa.Integer(), nullable=False, comment="ID"),
        sa.Column(
            "name", sa.String(), nullable=False, comment="Name der Gemeindeeinheit"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bool_erweitert_id"), "bool_erweitert", ["id"], unique=True)

    connection = op.get_bind()

    connection.execute(
        sa.text(
            """
        INSERT INTO bool_erweitert (name) VALUES
            ('Ja'),
            ('Nein'),
            ('Weiß nicht')
    """
        )
    )
    op.create_table(
        "klimarelevanzpruefung_energiestandard",
        sa.Column("id", sa.Integer(), nullable=False, comment="ID"),
        sa.Column("name", sa.String(), nullable=False, comment="Name des Bauvorhabens"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_klimarelevanzpruefung_energiestandard_id"),
        "klimarelevanzpruefung_energiestandard",
        ["id"],
        unique=True,
    )
    op.create_table(
        "klimarelevanzpruefung_vorhaben",
        sa.Column("id", sa.Integer(), nullable=False, comment="ID"),
        sa.Column("name", sa.String(), nullable=False, comment="Name des Bauvorhabens"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_klimarelevanzpruefung_vorhaben_id"),
        "klimarelevanzpruefung_vorhaben",
        ["id"],
        unique=True,
    )
    op.create_table(
        "gemeinde_einheit",
        sa.Column("id", sa.Integer(), nullable=False, comment="Gemeindeeinehit ID"),
        sa.Column(
            "name", sa.String(), nullable=False, comment="Name der Gemeindeeinheit"
        ),
        sa.Column(
            "rolle_id",
            sa.Integer(),
            nullable=True,
            comment="Rollen ID der Gemeindeeinheit",
        ),
        sa.Column(
            "gemeinde_id",
            sa.Integer(),
            nullable=False,
            comment="Gemeinde ID mit der die Einheit verknüpft ist",
        ),
        sa.ForeignKeyConstraint(["gemeinde_id"], ["gemeinde.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rolle_id"], ["user_rolle.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gemeinde_einheit_id"), "gemeinde_einheit", ["id"], unique=True
    )
    op.create_table(
        "klimarelevanzpruefung_vorhaben_energiestandard",
        sa.Column("vorhaben_id", sa.Integer(), nullable=True),
        sa.Column("energiestandard_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["energiestandard_id"],
            ["klimarelevanzpruefung_energiestandard.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vorhaben_id"], ["klimarelevanzpruefung_vorhaben.id"], ondelete="CASCADE"
        ),
    )

    connection.execute(
        sa.text(
            """
        INSERT INTO klimarelevanzpruefung_vorhaben (id, name) VALUES
            (1, 'Neubau'),
            (2, 'Anbau'),
            (3, 'Umbau'),
            (4, 'Sanierung'),
            (5, 'Abriss')
        """
        )
    )

    connection.execute(
        sa.text(
            """
        INSERT INTO klimarelevanzpruefung_energiestandard (id, name) VALUES
            (1, 'kein Standard'),
            (2, 'KfW-Effizienzhaus 155'),
            (3, 'KfW-Effizienzhaus 100'),
            (4, 'KfW-Effizienzhaus 85'),
            (5, 'KfW-Effizienzhaus 70'),
            (6, 'KfW-Effizienzhaus 55'),
            (7, 'KfW-Effizienzhaus 40 (Plus)'),
            (8, 'Passivhaus (PHPP)')
        """
        )
    )

    connection.execute(
        sa.text(
            """
        INSERT INTO klimarelevanzpruefung_vorhaben_energiestandard (vorhaben_id, energiestandard_id) VALUES
            -- Neubau (1) & Anbau (2): only 6,7,8
            (1, 6), (1, 7), (1, 8),
            (2, 6), (2, 7), (2, 8),
            -- Umbau (3) & Sanierung (4): all options 1..8
            (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8),
            (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8)
        """
        )
    )
    op.create_table(
        "klimarelevanzpruefung_eingabe_fb1",
        sa.Column("id", sa.Integer(), nullable=False, comment="Gemeindeeinehit ID"),
        sa.Column("a1q1", sa.Integer(), nullable=False, comment="Teil 1 Frage 1"),
        sa.Column("a1q2", sa.String(), nullable=True, comment="Teil 1 Frage 2"),
        sa.Column("a1q3", sa.Integer(), nullable=True, comment="Teil 1 Frage 3"),
        sa.Column("a1q4", sa.String(), nullable=True, comment="Teil 1 Frage 4"),
        sa.Column("a1q5", sa.String(), nullable=True, comment="Teil 1 Frage 5"),
        sa.Column("a2q1", sa.Integer(), nullable=False, comment="Teil 2 Frage 1"),
        sa.Column("a2q2", sa.Integer(), nullable=True, comment="Teil 2 Frage 2"),
        sa.Column("a2q3", sa.Integer(), nullable=True, comment="Teil 2 Frage 3"),
        sa.Column("a2q4", sa.Integer(), nullable=True, comment="Teil 2 Frage 4"),
        sa.Column("a2q5", sa.String(), nullable=True, comment="Teil 2 Frage 5"),
        sa.Column("a2q6", sa.Integer(), nullable=True, comment="Teil 2 Frage 6"),
        sa.Column("a2q7", sa.String(), nullable=True, comment="Teil 2 Frage 7"),
        sa.Column("a2q8", sa.Integer(), nullable=True, comment="Teil 2 Frage 8"),
        sa.Column("a2q9", sa.String(), nullable=True, comment="Teil 2 Frage 9"),
        sa.Column("a2q10", sa.Integer(), nullable=True, comment="Teil 2 Frage 10"),
        sa.Column("a2q11", sa.String(), nullable=True, comment="Teil 2 Frage 11"),
        sa.Column("a2q12", sa.Integer(), nullable=True, comment="Teil 2 Frage 12"),
        sa.Column("a2q13", sa.String(), nullable=True, comment="Teil 2 Frage 13"),
        sa.Column("a2q14", sa.Integer(), nullable=True, comment="Teil 2 Frage 14"),
        sa.Column("a2q15", sa.String(), nullable=True, comment="Teil 2 Frage 15"),
        sa.Column("a3q1", sa.Integer(), nullable=False, comment="Teil 3 Frage 1"),
        sa.Column("a3q2", sa.Float(), nullable=True, comment="Teil 3 Frage 2"),
        sa.Column("a3q3", sa.String(), nullable=True, comment="Teil 3 Frage 3"),
        sa.Column("a3q4", sa.Integer(), nullable=True, comment="Teil 3 Frage 4"),
        sa.Column("a3q5", sa.String(), nullable=True, comment="Teil 3 Frage 3"),
        sa.Column("a3q6", sa.String(), nullable=True, comment="Teil 3 Frage 4"),
        sa.Column("a4q1", sa.Integer(), nullable=False, comment="Teil 4 Frage 1"),
        sa.Column("a4q2", sa.Float(), nullable=True, comment="Teil 4 Frage 2"),
        sa.Column("a4q3", sa.String(), nullable=True, comment="Teil 4 Frage 3"),
        sa.Column("a4q4", sa.Integer(), nullable=True, comment="Teil 4 Frage 4"),
        sa.Column("a5q1", sa.Integer(), nullable=False, comment="Teil 5 Frage 1"),
        sa.Column("a5q2", sa.String(), nullable=True, comment="Teil 5 Frage 2"),
        sa.Column("a5q3", sa.String(), nullable=True, comment="Teil 5 Frage 3"),
        sa.Column("a5q4", sa.Integer(), nullable=True, comment="Teil 5 Frage 4"),
        sa.Column("a6q1", sa.Integer(), nullable=False, comment="Teil 6 Frage 1"),
        sa.Column("a6q2", sa.String(), nullable=True, comment="Teil 6 Frage 2"),
        sa.Column("a6q3", sa.Integer(), nullable=True, comment="Teil 6 Frage 3"),
        sa.Column("a6q4", sa.String(), nullable=True, comment="Teil 6 Frage 4"),
        sa.Column("a6q5", sa.String(), nullable=True, comment="Teil 6 Frage 5"),
        sa.Column("a7q1", sa.Integer(), nullable=False, comment="Teil 7 Frage 1"),
        sa.Column("a7q2", sa.String(), nullable=True, comment="Teil 7 Frage 2"),
        sa.Column("a8q1", sa.Integer(), nullable=False, comment="Teil 7 Frage 1"),
        sa.Column("a8q2", sa.String(), nullable=True, comment="Teil 7 Frage 2"),
        sa.Column("gemeinde_id", sa.Integer(), nullable=False, comment="Gemeinde ID"),
        sa.Column(
            "erstellt_von",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
            comment="User ID des Erstellers",
        ),
        sa.Column(
            "zuletzt_bearbeitet_von",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
            comment="User ID des zuletzt bearbeitenden Benutzers",
        ),
        sa.ForeignKeyConstraint(["a1q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a1q3"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a2q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a2q10"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a2q12"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a2q14"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["a2q2"], ["klimarelevanzpruefung_vorhaben.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["a2q3"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["a2q4"], ["klimarelevanzpruefung_energiestandard.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["a2q6"], ["klimarelevanzpruefung_energiestandard.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["a2q8"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a3q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a3q4"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a4q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a4q4"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a5q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a5q4"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a6q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a6q3"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a7q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a8q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["erstellt_von"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["gemeinde_id"], ["gemeinde.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["zuletzt_bearbeitet_von"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_klimarelevanzpruefung_eingabe_fb1_id"),
        "klimarelevanzpruefung_eingabe_fb1",
        ["id"],
        unique=True,
    )
    op.create_table(
        "klimarelevanzpruefung_eingabe_fb2",
        sa.Column("id", sa.Integer(), nullable=False, comment="Gemeindeeinehit ID"),
        sa.Column("b1q1", sa.Integer(), nullable=False, comment="Teil 1 Frage 1"),
        sa.Column("b1q2", sa.Integer(), nullable=True, comment="Teil 1 Frage 2"),
        sa.Column("b1q3", sa.String(), nullable=True, comment="Teil 1 Frage 3"),
        sa.Column("b1q4", sa.Integer(), nullable=True, comment="Teil 1 Frage 4"),
        sa.Column("b1q5", sa.String(), nullable=True, comment="Teil 1 Frage 5"),
        sa.Column("b1q6", sa.Integer(), nullable=True, comment="Teil 1 Frage 6"),
        sa.Column("b1q7", sa.String(), nullable=True, comment="Teil 1 Frage 7"),
        sa.Column("b1q8", sa.String(), nullable=True, comment="Teil 1 Frage 8"),
        sa.Column("b1q9", sa.Integer(), nullable=True, comment="Teil 1 Frage 9"),
        sa.Column("b1q10", sa.String(), nullable=True, comment="Teil 1 Frage 10"),
        sa.Column("b1q11", sa.String(), nullable=True, comment="Teil 1 Frage 11"),
        sa.Column("b1q12", sa.Integer(), nullable=True, comment="Teil 1 Frage 12"),
        sa.Column("b1q13", sa.String(), nullable=True, comment="Teil 1 Frage 13"),
        sa.Column("b1q14", sa.String(), nullable=True, comment="Teil 1 Frage 14"),
        sa.Column("b1q15", sa.Integer(), nullable=True, comment="Teil 1 Frage 15"),
        sa.Column("b1q16", sa.String(), nullable=True, comment="Teil 1 Frage 16"),
        sa.Column("b1q17", sa.String(), nullable=True, comment="Teil 1 Frage 17"),
        sa.Column("b1q18", sa.Integer(), nullable=True, comment="Teil 1 Frage 18"),
        sa.Column("b1q19", sa.String(), nullable=True, comment="Teil 1 Frage 19"),
        sa.Column("b1q20", sa.String(), nullable=True, comment="Teil 1 Frage 20"),
        sa.Column("a2q1", sa.Integer(), nullable=False, comment="Teil 2 Frage 1"),
        sa.Column("a2q2", sa.String(), nullable=True, comment="Teil 2 Frage 2"),
        sa.Column("a2q3", sa.String(), nullable=True, comment="Teil 2 Frage 3"),
        sa.Column("a2q4", sa.Integer(), nullable=True, comment="Teil 2 Frage 4"),
        sa.Column("a2q5", sa.String(), nullable=True, comment="Teil 2 Frage 5"),
        sa.Column("gemeinde_id", sa.Integer(), nullable=False, comment="Gemeinde ID"),
        sa.Column(
            "erstellt_von",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
            comment="User ID des Erstellers",
        ),
        sa.Column(
            "zuletzt_bearbeitet_von",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
            comment="User ID des zuletzt bearbeitenden Benutzers",
        ),
        sa.ForeignKeyConstraint(["a2q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["a2q4"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["b1q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["b1q12"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["b1q15"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["b1q18"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["b1q2"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["b1q4"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["b1q6"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["b1q9"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["erstellt_von"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["gemeinde_id"], ["gemeinde.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["zuletzt_bearbeitet_von"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_klimarelevanzpruefung_eingabe_fb2_id"),
        "klimarelevanzpruefung_eingabe_fb2",
        ["id"],
        unique=True,
    )
    op.create_table(
        "klimarelevanzpruefung_eingabe_fb3",
        sa.Column("id", sa.Integer(), nullable=False, comment="Gemeindeeinehit ID"),
        sa.Column("c1q1", sa.Integer(), nullable=False, comment="Teil 1 Frage 1"),
        sa.Column("c1q2", sa.Integer(), nullable=True, comment="Teil 1 Frage 2"),
        sa.Column("c1q3", sa.String(), nullable=True, comment="Teil 1 Frage 3"),
        sa.Column("c1q4", sa.Integer(), nullable=True, comment="Teil 1 Frage 4"),
        sa.Column("c1q5", sa.String(), nullable=True, comment="Teil 1 Frage 5"),
        sa.Column("c1q6", sa.Integer(), nullable=True, comment="Teil 1 Frage 6"),
        sa.Column("c1q7", sa.String(), nullable=True, comment="Teil 1 Frage 7"),
        sa.Column("c1q8", sa.Integer(), nullable=True, comment="Teil 1 Frage 8"),
        sa.Column("c1q9", sa.String(), nullable=True, comment="Teil 1 Frage 9"),
        sa.Column("c2q1", sa.Integer(), nullable=False, comment="Teil 2 Frage 1"),
        sa.Column("c2q2", sa.Integer(), nullable=True, comment="Teil 2 Frage 2"),
        sa.Column("c2q3", sa.String(), nullable=True, comment="Teil 2 Frage 3"),
        sa.Column("c2q4", sa.Integer(), nullable=True, comment="Teil 2 Frage 4"),
        sa.Column("c2q5", sa.String(), nullable=True, comment="Teil 2 Frage 5"),
        sa.Column("c2q6", sa.Integer(), nullable=True, comment="Teil 2 Frage 6"),
        sa.Column("c2q7", sa.String(), nullable=True, comment="Teil 2 Frage 7"),
        sa.Column("c2q8", sa.Integer(), nullable=True, comment="Teil 2 Frage 8"),
        sa.Column("c2q9", sa.String(), nullable=True, comment="Teil 2 Frage 9"),
        sa.Column("gemeinde_id", sa.Integer(), nullable=False, comment="Gemeinde ID"),
        sa.Column(
            "erstellt_von",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
            comment="User ID des Erstellers",
        ),
        sa.Column(
            "zuletzt_bearbeitet_von",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
            comment="User ID des zuletzt bearbeitenden Benutzers",
        ),
        sa.ForeignKeyConstraint(["c1q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["c1q2"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["c1q4"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["c1q6"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["c1q8"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["c2q1"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["c2q2"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["c2q4"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["c2q6"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["c2q8"], ["bool_erweitert.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["erstellt_von"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["gemeinde_id"], ["gemeinde.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["zuletzt_bearbeitet_von"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_klimarelevanzpruefung_eingabe_fb3_id"),
        "klimarelevanzpruefung_eingabe_fb3",
        ["id"],
        unique=True,
    )
    op.create_table(
        "klimarelevanzpruefung_eingabe_fb4",
        sa.Column("id", sa.Integer(), nullable=False, comment="Gemeindeeinehit ID"),
        sa.Column("d1q1", sa.String(), nullable=False, comment="Teil 1 Frage 1"),
        sa.Column("d2q1", sa.String(), nullable=False, comment="Teil 2 Frage 1"),
        sa.Column("gemeinde_id", sa.Integer(), nullable=False, comment="Gemeinde ID"),
        sa.Column(
            "erstellt_von",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
            comment="User ID des Erstellers",
        ),
        sa.Column(
            "zuletzt_bearbeitet_von",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
            comment="User ID des zuletzt bearbeitenden Benutzers",
        ),
        sa.ForeignKeyConstraint(["erstellt_von"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["gemeinde_id"], ["gemeinde.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["zuletzt_bearbeitet_von"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_klimarelevanzpruefung_eingabe_fb4_id"),
        "klimarelevanzpruefung_eingabe_fb4",
        ["id"],
        unique=True,
    )
    op.create_table(
        "klimarelevanzpruefung_eingabe",
        sa.Column("id", sa.Integer(), nullable=False, comment="Gemeindeeinehit ID"),
        sa.Column(
            "name", sa.String(), nullable=False, comment="Name der Gemeindeeinheit"
        ),
        sa.Column("f1", sa.Boolean(), nullable=False, comment="Fragebogen 1 notwendig"),
        sa.Column(
            "fb1_id",
            sa.Integer(),
            nullable=True,
            comment="Verknüpfung zum Mobilitätscheck Eingabe, falls Fragebogen 1 notwendig ist",
        ),
        sa.Column("f2", sa.Boolean(), nullable=False, comment="Fragebogen 2 notwendig"),
        sa.Column(
            "fb2_id",
            sa.Integer(),
            nullable=True,
            comment="Verknüpfung zum Mobilitätscheck Eingabe, falls Fragebogen 2 notwendig ist",
        ),
        sa.Column("f3", sa.Boolean(), nullable=False, comment="Fragebogen 3 notwendig"),
        sa.Column(
            "fb3_id",
            sa.Integer(),
            nullable=True,
            comment="Verknüpfung zum Mobilitätscheck Eingabe, falls Fragebogen 3 notwendig ist",
        ),
        sa.Column("f4", sa.Boolean(), nullable=False, comment="Fragebogen 4 notwendig"),
        sa.Column(
            "fb4_id",
            sa.Integer(),
            nullable=True,
            comment="Verknüpfung zum Mobilitätscheck Eingabe, falls Fragebogen 4 notwendig ist",
        ),
        sa.Column("f5", sa.Boolean(), nullable=False, comment="Fragebogen 5 notwendig"),
        sa.Column(
            "gemeinde_id",
            sa.Integer(),
            nullable=False,
            comment="Gemeinde ID mit der die Einheit verknüpft ist",
        ),
        sa.Column(
            "erstellt_von",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
            comment="User ID des Erstellers",
        ),
        sa.Column(
            "zuletzt_bearbeitet_von",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
            comment="User ID des zuletzt bearbeitenden Benutzers",
        ),
        sa.ForeignKeyConstraint(["erstellt_von"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["fb1_id"], ["klimarelevanzpruefung_eingabe_fb1.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["fb2_id"], ["klimarelevanzpruefung_eingabe_fb2.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["fb3_id"], ["klimarelevanzpruefung_eingabe_fb3.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["fb4_id"], ["klimarelevanzpruefung_eingabe_fb4.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["gemeinde_id"], ["gemeinde.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["zuletzt_bearbeitet_von"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_klimarelevanzpruefung_eingabe_id"),
        "klimarelevanzpruefung_eingabe",
        ["id"],
        unique=True,
    )
    op.create_table(
        "magistratsvorlage_tag",
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.Column("magistratsvorlage_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["magistratsvorlage_id"], ["magistratsvorlage.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
    )
    op.add_column(
        "user",
        sa.Column(
            "einheit_id",
            sa.Integer(),
            sa.ForeignKey("gemeinde_einheit.id", ondelete="SET NULL"),
            nullable=True,
            comment="Einheit des Benutzers innerhalb der Gemeinde",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "einheit_id")
    op.drop_table("magistratsvorlage_tag")
    op.drop_index(
        op.f("ix_klimarelevanzpruefung_eingabe_id"),
        table_name="klimarelevanzpruefung_eingabe",
    )
    op.drop_table("klimarelevanzpruefung_eingabe")
    op.drop_index(
        op.f("ix_klimarelevanzpruefung_eingabe_fb4_id"),
        table_name="klimarelevanzpruefung_eingabe_fb4",
    )
    op.drop_table("klimarelevanzpruefung_eingabe_fb4")
    op.drop_index(
        op.f("ix_klimarelevanzpruefung_eingabe_fb3_id"),
        table_name="klimarelevanzpruefung_eingabe_fb3",
    )
    op.drop_table("klimarelevanzpruefung_eingabe_fb3")
    op.drop_index(
        op.f("ix_klimarelevanzpruefung_eingabe_fb2_id"),
        table_name="klimarelevanzpruefung_eingabe_fb2",
    )
    op.drop_table("klimarelevanzpruefung_eingabe_fb2")
    op.drop_index(
        op.f("ix_klimarelevanzpruefung_eingabe_fb1_id"),
        table_name="klimarelevanzpruefung_eingabe_fb1",
    )
    op.drop_table("klimarelevanzpruefung_eingabe_fb1")
    op.drop_table("klimarelevanzpruefung_vorhaben_energiestandard")
    op.drop_index(op.f("ix_gemeinde_einheit_id"), table_name="gemeinde_einheit")
    op.drop_table("gemeinde_einheit")
    op.drop_index(
        op.f("ix_klimarelevanzpruefung_vorhaben_id"),
        table_name="klimarelevanzpruefung_vorhaben",
    )
    op.drop_table("klimarelevanzpruefung_vorhaben")
    op.drop_index(
        op.f("ix_klimarelevanzpruefung_energiestandard_id"),
        table_name="klimarelevanzpruefung_energiestandard",
    )
    op.drop_table("klimarelevanzpruefung_energiestandard")
    op.drop_index(op.f("ix_bool_erweitert_id"), table_name="bool_erweitert")
    op.drop_table("bool_erweitert")
    # ### end Alembic commands ###
