"""update ondelete

Revision ID: bc641731e773
Revises: 925d59f158e5
Create Date: 2025-03-07 15:57:23.989539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc641731e773'
down_revision: Union[str, None] = '925d59f158e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('climate_submission_municipality_id_fkey', 'climate_submission', type_='foreignkey')
    op.drop_constraint('climate_submission_created_by_fkey', 'climate_submission', type_='foreignkey')
    op.drop_constraint('climate_submission_last_edited_by_fkey', 'climate_submission', type_='foreignkey')
    op.create_foreign_key(None, 'climate_submission', 'user', ['last_edited_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'climate_submission', 'municipality', ['municipality_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'climate_submission', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('indicator_last_edited_by_fkey', 'indicator', type_='foreignkey')
    op.drop_constraint('indicator_municipality_id_fkey', 'indicator', type_='foreignkey')
    op.drop_constraint('indicator_created_by_fkey', 'indicator', type_='foreignkey')
    op.create_foreign_key(None, 'indicator', 'municipality', ['municipality_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'indicator', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'indicator', 'user', ['last_edited_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('main_objective_municipality_id_fkey', 'main_objective', type_='foreignkey')
    op.drop_constraint('main_objective_created_by_fkey', 'main_objective', type_='foreignkey')
    op.drop_constraint('main_objective_last_edited_by_fkey', 'main_objective', type_='foreignkey')
    op.create_foreign_key(None, 'main_objective', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'main_objective', 'user', ['last_edited_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'main_objective', 'municipality', ['municipality_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('mobility_submission_last_edited_by_fkey', 'mobility_submission', type_='foreignkey')
    op.drop_constraint('mobility_submission_municipality_id_fkey', 'mobility_submission', type_='foreignkey')
    op.drop_constraint('mobility_submission_created_by_fkey', 'mobility_submission', type_='foreignkey')
    op.create_foreign_key(None, 'mobility_submission', 'municipality', ['municipality_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'mobility_submission', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'mobility_submission', 'user', ['last_edited_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('mobility_result_sub_sub_objective_id_fkey', 'mobility_subresult', type_='foreignkey')
    op.create_foreign_key(None, 'mobility_subresult', 'sub_objective', ['sub_objective_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sub_objective_created_by_fkey', 'sub_objective', type_='foreignkey')
    op.drop_constraint('sub_objective_last_edited_by_fkey', 'sub_objective', type_='foreignkey')
    op.drop_constraint('sub_objective_municipality_id_fkey', 'sub_objective', type_='foreignkey')
    op.drop_constraint('sub_objective_main_objective_id_fkey', 'sub_objective', type_='foreignkey')
    op.create_foreign_key(None, 'sub_objective', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sub_objective', 'main_objective', ['main_objective_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sub_objective', 'municipality', ['municipality_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sub_objective', 'user', ['last_edited_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('tag_municipality_id_fkey', 'tag', type_='foreignkey')
    op.drop_constraint('tag_created_by_fkey', 'tag', type_='foreignkey')
    op.drop_constraint('tag_last_edited_by_fkey', 'tag', type_='foreignkey')
    op.create_foreign_key(None, 'tag', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tag', 'user', ['last_edited_by'], ['id'], ondelete='SET NULl')
    op.create_foreign_key(None, 'tag', 'municipality', ['municipality_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('text_block_municipality_id_fkey', 'text_block', type_='foreignkey')
    op.drop_constraint('text_block_created_by_fkey', 'text_block', type_='foreignkey')
    op.drop_constraint('text_block_last_edited_by_fkey', 'text_block', type_='foreignkey')
    op.create_foreign_key(None, 'text_block', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'text_block', 'municipality', ['municipality_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'text_block', 'user', ['last_edited_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('user_municipality_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'municipality', ['municipality_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_municipality_id_fkey', 'user', 'municipality', ['municipality_id'], ['id'])
    op.drop_constraint(None, 'text_block', type_='foreignkey')
    op.drop_constraint(None, 'text_block', type_='foreignkey')
    op.drop_constraint(None, 'text_block', type_='foreignkey')
    op.create_foreign_key('text_block_last_edited_by_fkey', 'text_block', 'user', ['last_edited_by'], ['id'])
    op.create_foreign_key('text_block_created_by_fkey', 'text_block', 'user', ['created_by'], ['id'])
    op.create_foreign_key('text_block_municipality_id_fkey', 'text_block', 'municipality', ['municipality_id'], ['id'])
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.create_foreign_key('tag_last_edited_by_fkey', 'tag', 'user', ['last_edited_by'], ['id'])
    op.create_foreign_key('tag_created_by_fkey', 'tag', 'user', ['created_by'], ['id'])
    op.create_foreign_key('tag_municipality_id_fkey', 'tag', 'municipality', ['municipality_id'], ['id'])
    op.drop_constraint(None, 'sub_objective', type_='foreignkey')
    op.drop_constraint(None, 'sub_objective', type_='foreignkey')
    op.drop_constraint(None, 'sub_objective', type_='foreignkey')
    op.drop_constraint(None, 'sub_objective', type_='foreignkey')
    op.create_foreign_key('sub_objective_main_objective_id_fkey', 'sub_objective', 'main_objective', ['main_objective_id'], ['id'])
    op.create_foreign_key('sub_objective_municipality_id_fkey', 'sub_objective', 'municipality', ['municipality_id'], ['id'])
    op.create_foreign_key('sub_objective_last_edited_by_fkey', 'sub_objective', 'user', ['last_edited_by'], ['id'])
    op.create_foreign_key('sub_objective_created_by_fkey', 'sub_objective', 'user', ['created_by'], ['id'])
    op.drop_constraint(None, 'mobility_subresult', type_='foreignkey')
    op.create_foreign_key('mobility_result_sub_sub_objective_id_fkey', 'mobility_subresult', 'sub_objective', ['sub_objective_id'], ['id'])
    op.drop_constraint(None, 'mobility_submission', type_='foreignkey')
    op.drop_constraint(None, 'mobility_submission', type_='foreignkey')
    op.drop_constraint(None, 'mobility_submission', type_='foreignkey')
    op.create_foreign_key('mobility_submission_created_by_fkey', 'mobility_submission', 'user', ['created_by'], ['id'])
    op.create_foreign_key('mobility_submission_municipality_id_fkey', 'mobility_submission', 'municipality', ['municipality_id'], ['id'])
    op.create_foreign_key('mobility_submission_last_edited_by_fkey', 'mobility_submission', 'user', ['last_edited_by'], ['id'])
    op.drop_constraint(None, 'main_objective', type_='foreignkey')
    op.drop_constraint(None, 'main_objective', type_='foreignkey')
    op.drop_constraint(None, 'main_objective', type_='foreignkey')
    op.create_foreign_key('main_objective_last_edited_by_fkey', 'main_objective', 'user', ['last_edited_by'], ['id'])
    op.create_foreign_key('main_objective_created_by_fkey', 'main_objective', 'user', ['created_by'], ['id'])
    op.create_foreign_key('main_objective_municipality_id_fkey', 'main_objective', 'municipality', ['municipality_id'], ['id'])
    op.drop_constraint(None, 'indicator', type_='foreignkey')
    op.drop_constraint(None, 'indicator', type_='foreignkey')
    op.drop_constraint(None, 'indicator', type_='foreignkey')
    op.create_foreign_key('indicator_created_by_fkey', 'indicator', 'user', ['created_by'], ['id'])
    op.create_foreign_key('indicator_municipality_id_fkey', 'indicator', 'municipality', ['municipality_id'], ['id'])
    op.create_foreign_key('indicator_last_edited_by_fkey', 'indicator', 'user', ['last_edited_by'], ['id'])
    op.drop_constraint(None, 'climate_submission', type_='foreignkey')
    op.drop_constraint(None, 'climate_submission', type_='foreignkey')
    op.drop_constraint(None, 'climate_submission', type_='foreignkey')
    op.create_foreign_key('climate_submission_last_edited_by_fkey', 'climate_submission', 'user', ['last_edited_by'], ['id'])
    op.create_foreign_key('climate_submission_created_by_fkey', 'climate_submission', 'user', ['created_by'], ['id'])
    op.create_foreign_key('climate_submission_municipality_id_fkey', 'climate_submission', 'municipality', ['municipality_id'], ['id'])
    # ### end Alembic commands ###
