"""name chekcs

Revision ID: c77fba81521e
Revises: 1f5cbc86b396
Create Date: 2025-07-29 16:20:06.244053

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c77fba81521e"
down_revision: Union[str, None] = "1f5cbc86b396"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "klimacheck_eingabe",
        sa.Column(
            "name", sa.String(), nullable=True, comment="Name der Klimacheck-Eingabe"
        ),
    )
    op.add_column(
        "mobilitaetscheck_eingabe",
        sa.Column(
            "name",
            sa.String(),
            nullable=True,
            comment="Name der Mobilitätscheck-Eingabe",
        ),
    )

    # Use raw SQL to populate the name columns from the magistratsvorlage table
    op.execute(
        """
        UPDATE klimacheck_eingabe
        SET name = magistratsvorlage.name
        FROM magistratsvorlage
        WHERE klimacheck_eingabe.magistratsvorlage_id = magistratsvorlage.id
    """
    )

    op.execute(
        """
        UPDATE mobilitaetscheck_eingabe
        SET name = magistratsvorlage.name
        FROM magistratsvorlage
        WHERE mobilitaetscheck_eingabe.magistratsvorlage_id = magistratsvorlage.id
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mobilitaetscheck_eingabe", "name")
    op.drop_column("klimacheck_eingabe", "name")
    # ### end Alembic commands ###
