"""add created_at to klimareleanzpruefung

Revision ID: e6453544b628
Revises: 475d7faf351c
Create Date: 2026-02-03 17:43:19.758362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6453544b628'
down_revision: Union[str, None] = '475d7faf351c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first for existing entries
    op.add_column('klimarelevanzpruefung_eingabe', sa.Column('erstellt_am', sa.DateTime(), nullable=True, comment='Zeitpunkt der Erstellung'))
    # Set default value for existing entries (today's date: 2026-02-03)
    op.execute("UPDATE klimarelevanzpruefung_eingabe SET erstellt_am = '2026-02-03 00:00:00' WHERE erstellt_am IS NULL")
    # Now make it NOT NULL with server default for future entries
    op.alter_column('klimarelevanzpruefung_eingabe', 'erstellt_am', nullable=False, server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('klimarelevanzpruefung_eingabe', 'erstellt_am')
    # ### end Alembic commands ###
