"""fix typo

Revision ID: fda26a8974b8
Revises: 83a75db6b1d5
Create Date: 2025-07-31 18:36:11.333763

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fda26a8974b8"
down_revision: Union[str, None] = "83a75db6b1d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "magistratsvorlage",
        "zuletzt_bearbeiter_von",
        new_column_name="zuletzt_bearbeitet_von",
    )

    op.drop_constraint(
        "magistratsvorlage_zuletzt_bearbeiter_von_fkey",
        "magistratsvorlage",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "magistratsvorlage",
        "user",
        ["zuletzt_bearbeitet_von"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "magistratsvorlage",
        "zuletzt_bearbeitet_von",
        new_column_name="zuletzt_bearbeiter_von",
    )
    op.drop_constraint(None, "magistratsvorlage", type_="foreignkey")
    op.create_foreign_key(
        "magistratsvorlage_zuletzt_bearbeiter_von_fkey",
        "magistratsvorlage",
        "user",
        ["zuletzt_bearbeiter_von"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
